apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-service
spec:
  replicas: 1  # Test için tek replica kullanıyoruz
  selector:
    matchLabels:
      app: smart-service
  template:
    metadata:
      labels:
        app: smart-service
    spec:
      containers:
      - name: smart-service
        image: smart-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 50051
          name: grpc
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: smartdb
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: password123
        readinessProbe:
          tcpSocket:
            port: grpc
          initialDelaySeconds: 5
          periodSeconds: 10