apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-service
  template:
    metadata:
      labels:
        app: smart-service
    spec:
      containers:
      - name: smart-service
        image: smart-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 50051
          name: grpc
        - containerPort: 8000
          name: metrics
        envFrom:
        - configMapRef:
            name: smart-service-config
        env:
          - name: DATABASE_URL
            value: "postgresql://postgres:password123@postgres:5432/smartdb"