apiVersion: v1
kind: Service
metadata:
  name: smart-service
spec:
  selector:
    app: smart-service
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
  - name: metrics
    port: 8000
    targetPort: 8000
  type: LoadBalancer