apiVersion: v1
kind: Service
metadata:
  name: smart-service
spec:
  selector:
    app: smart-service
  ports:
  - port: 50051
    targetPort: grpc
    name: grpc
    protocol: TCP
  type: LoadBalancer