# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import smart_service_pb2 as smart__service__pb2


class SmartServiceStub(object):
    """Ana servis tanımı
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateModel = channel.unary_unary(
                '/smart_service.SmartService/CreateModel',
                request_serializer=smart__service__pb2.CreateModelRequest.SerializeToString,
                response_deserializer=smart__service__pb2.SmartModel.FromString,
                )
        self.GetModel = channel.unary_unary(
                '/smart_service.SmartService/GetModel',
                request_serializer=smart__service__pb2.GetModelRequest.SerializeToString,
                response_deserializer=smart__service__pb2.SmartModel.FromString,
                )
        self.UpdateModel = channel.unary_unary(
                '/smart_service.SmartService/UpdateModel',
                request_serializer=smart__service__pb2.UpdateModelRequest.SerializeToString,
                response_deserializer=smart__service__pb2.SmartModel.FromString,
                )
        self.DeleteModel = channel.unary_unary(
                '/smart_service.SmartService/DeleteModel',
                request_serializer=smart__service__pb2.DeleteModelRequest.SerializeToString,
                response_deserializer=smart__service__pb2.SmartModel.FromString,
                )
        self.ListModels = channel.unary_unary(
                '/smart_service.SmartService/ListModels',
                request_serializer=smart__service__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=smart__service__pb2.ListModelsResponse.FromString,
                )


class SmartServiceServicer(object):
    """Ana servis tanımı
    """

    def CreateModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SmartServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateModel': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateModel,
                    request_deserializer=smart__service__pb2.CreateModelRequest.FromString,
                    response_serializer=smart__service__pb2.SmartModel.SerializeToString,
            ),
            'GetModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModel,
                    request_deserializer=smart__service__pb2.GetModelRequest.FromString,
                    response_serializer=smart__service__pb2.SmartModel.SerializeToString,
            ),
            'UpdateModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateModel,
                    request_deserializer=smart__service__pb2.UpdateModelRequest.FromString,
                    response_serializer=smart__service__pb2.SmartModel.SerializeToString,
            ),
            'DeleteModel': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteModel,
                    request_deserializer=smart__service__pb2.DeleteModelRequest.FromString,
                    response_serializer=smart__service__pb2.SmartModel.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=smart__service__pb2.ListModelsRequest.FromString,
                    response_serializer=smart__service__pb2.ListModelsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'smart_service.SmartService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SmartService(object):
    """Ana servis tanımı
    """

    @staticmethod
    def CreateModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/smart_service.SmartService/CreateModel',
            smart__service__pb2.CreateModelRequest.SerializeToString,
            smart__service__pb2.SmartModel.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/smart_service.SmartService/GetModel',
            smart__service__pb2.GetModelRequest.SerializeToString,
            smart__service__pb2.SmartModel.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/smart_service.SmartService/UpdateModel',
            smart__service__pb2.UpdateModelRequest.SerializeToString,
            smart__service__pb2.SmartModel.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/smart_service.SmartService/DeleteModel',
            smart__service__pb2.DeleteModelRequest.SerializeToString,
            smart__service__pb2.SmartModel.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/smart_service.SmartService/ListModels',
            smart__service__pb2.ListModelsRequest.SerializeToString,
            smart__service__pb2.ListModelsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
