# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smart_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13smart_service.proto\x12\rsmart_service\"[\n\nSmartModel\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\"f\n\x0cSmartFeature\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08model_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x15\n\rfunction_type\x18\x05 \x01(\t\">\n\x12\x43reateModelRequest\x12(\n\x05model\x18\x01 \x01(\x0b\x32\x19.smart_service.SmartModel\"\x1d\n\x0fGetModelRequest\x12\n\n\x02id\x18\x01 \x01(\t\"3\n\x11ListModelsRequest\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\"?\n\x12ListModelsResponse\x12)\n\x06models\x18\x01 \x03(\x0b\x32\x19.smart_service.SmartModel\"c\n\x12UpdateModelRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\" \n\x12\x44\x65leteModelRequest\x12\n\n\x02id\x18\x01 \x01(\t2\x8f\x03\n\x0cSmartService\x12K\n\x0b\x43reateModel\x12!.smart_service.CreateModelRequest\x1a\x19.smart_service.SmartModel\x12\x45\n\x08GetModel\x12\x1e.smart_service.GetModelRequest\x1a\x19.smart_service.SmartModel\x12K\n\x0bUpdateModel\x12!.smart_service.UpdateModelRequest\x1a\x19.smart_service.SmartModel\x12K\n\x0b\x44\x65leteModel\x12!.smart_service.DeleteModelRequest\x1a\x19.smart_service.SmartModel\x12Q\n\nListModels\x12 .smart_service.ListModelsRequest\x1a!.smart_service.ListModelsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'smart_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SMARTMODEL']._serialized_start=38
  _globals['_SMARTMODEL']._serialized_end=129
  _globals['_SMARTFEATURE']._serialized_start=131
  _globals['_SMARTFEATURE']._serialized_end=233
  _globals['_CREATEMODELREQUEST']._serialized_start=235
  _globals['_CREATEMODELREQUEST']._serialized_end=297
  _globals['_GETMODELREQUEST']._serialized_start=299
  _globals['_GETMODELREQUEST']._serialized_end=328
  _globals['_LISTMODELSREQUEST']._serialized_start=330
  _globals['_LISTMODELSREQUEST']._serialized_end=381
  _globals['_LISTMODELSRESPONSE']._serialized_start=383
  _globals['_LISTMODELSRESPONSE']._serialized_end=446
  _globals['_UPDATEMODELREQUEST']._serialized_start=448
  _globals['_UPDATEMODELREQUEST']._serialized_end=547
  _globals['_DELETEMODELREQUEST']._serialized_start=549
  _globals['_DELETEMODELREQUEST']._serialized_end=581
  _globals['_SMARTSERVICE']._serialized_start=584
  _globals['_SMARTSERVICE']._serialized_end=983
# @@protoc_insertion_point(module_scope)
