# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from src  import smart_service_pb2 as smart__service__pb2


class SmartServiceStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateModel = channel.unary_unary(
                '/smart_service.SmartService/CreateModel',
                request_serializer=smart__service__pb2.CreateModelRequest.SerializeToString,
                response_deserializer=smart__service__pb2.SmartModel.FromString,
                )
        self.UpdateModel = channel.unary_unary(
                '/smart_service.SmartService/UpdateModel',
                request_serializer=smart__service__pb2.UpdateModelRequest.SerializeToString,
                response_deserializer=smart__service__pb2.SmartModel.FromString,
                )
        self.DeleteModel = channel.unary_unary(
                '/smart_service.SmartService/DeleteModel',
                request_serializer=smart__service__pb2.DeleteModelRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetModel = channel.unary_unary(
                '/smart_service.SmartService/GetModel',
                request_serializer=smart__service__pb2.GetModelRequest.SerializeToString,
                response_deserializer=smart__service__pb2.SmartModel.FromString,
                )
        self.SearchModels = channel.unary_unary(
                '/smart_service.SmartService/SearchModels',
                request_serializer=smart__service__pb2.SearchModelsRequest.SerializeToString,
                response_deserializer=smart__service__pb2.SearchModelsResponse.FromString,
                )
        self.AddFeature = channel.unary_unary(
                '/smart_service.SmartService/AddFeature',
                request_serializer=smart__service__pb2.AddFeatureRequest.SerializeToString,
                response_deserializer=smart__service__pb2.SmartFeature.FromString,
                )
        self.UpdateFeature = channel.unary_unary(
                '/smart_service.SmartService/UpdateFeature',
                request_serializer=smart__service__pb2.UpdateFeatureRequest.SerializeToString,
                response_deserializer=smart__service__pb2.SmartFeature.FromString,
                )
        self.DeleteFeature = channel.unary_unary(
                '/smart_service.SmartService/DeleteFeature',
                request_serializer=smart__service__pb2.DeleteFeatureRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetModelStatus = channel.unary_unary(
                '/smart_service.SmartService/GetModelStatus',
                request_serializer=smart__service__pb2.GetModelStatusRequest.SerializeToString,
                response_deserializer=smart__service__pb2.ModelStatusResponse.FromString,
                )


class SmartServiceServicer(object):
    """Service definition
    """

    def CreateModel(self, request, context):
        """Model operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddFeature(self, request, context):
        """Feature operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateFeature(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFeature(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelStatus(self, request, context):
        """Status operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SmartServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateModel': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateModel,
                    request_deserializer=smart__service__pb2.CreateModelRequest.FromString,
                    response_serializer=smart__service__pb2.SmartModel.SerializeToString,
            ),
            'UpdateModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateModel,
                    request_deserializer=smart__service__pb2.UpdateModelRequest.FromString,
                    response_serializer=smart__service__pb2.SmartModel.SerializeToString,
            ),
            'DeleteModel': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteModel,
                    request_deserializer=smart__service__pb2.DeleteModelRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModel,
                    request_deserializer=smart__service__pb2.GetModelRequest.FromString,
                    response_serializer=smart__service__pb2.SmartModel.SerializeToString,
            ),
            'SearchModels': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchModels,
                    request_deserializer=smart__service__pb2.SearchModelsRequest.FromString,
                    response_serializer=smart__service__pb2.SearchModelsResponse.SerializeToString,
            ),
            'AddFeature': grpc.unary_unary_rpc_method_handler(
                    servicer.AddFeature,
                    request_deserializer=smart__service__pb2.AddFeatureRequest.FromString,
                    response_serializer=smart__service__pb2.SmartFeature.SerializeToString,
            ),
            'UpdateFeature': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateFeature,
                    request_deserializer=smart__service__pb2.UpdateFeatureRequest.FromString,
                    response_serializer=smart__service__pb2.SmartFeature.SerializeToString,
            ),
            'DeleteFeature': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFeature,
                    request_deserializer=smart__service__pb2.DeleteFeatureRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetModelStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelStatus,
                    request_deserializer=smart__service__pb2.GetModelStatusRequest.FromString,
                    response_serializer=smart__service__pb2.ModelStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'smart_service.SmartService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SmartService(object):
    """Service definition
    """

    @staticmethod
    def CreateModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/smart_service.SmartService/CreateModel',
            smart__service__pb2.CreateModelRequest.SerializeToString,
            smart__service__pb2.SmartModel.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/smart_service.SmartService/UpdateModel',
            smart__service__pb2.UpdateModelRequest.SerializeToString,
            smart__service__pb2.SmartModel.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/smart_service.SmartService/DeleteModel',
            smart__service__pb2.DeleteModelRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/smart_service.SmartService/GetModel',
            smart__service__pb2.GetModelRequest.SerializeToString,
            smart__service__pb2.SmartModel.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/smart_service.SmartService/SearchModels',
            smart__service__pb2.SearchModelsRequest.SerializeToString,
            smart__service__pb2.SearchModelsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddFeature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/smart_service.SmartService/AddFeature',
            smart__service__pb2.AddFeatureRequest.SerializeToString,
            smart__service__pb2.SmartFeature.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateFeature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/smart_service.SmartService/UpdateFeature',
            smart__service__pb2.UpdateFeatureRequest.SerializeToString,
            smart__service__pb2.SmartFeature.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteFeature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/smart_service.SmartService/DeleteFeature',
            smart__service__pb2.DeleteFeatureRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetModelStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/smart_service.SmartService/GetModelStatus',
            smart__service__pb2.GetModelStatusRequest.SerializeToString,
            smart__service__pb2.ModelStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
